-- 1 up

CREATE TABLE version2os (
  id INTEGER PRIMARY KEY,
  version TEXT NOT NULL,
  os TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT "manual",
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastmod DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE banner2version (
  banner TEXT PRIMARY KEY,
  regexp BOOLEAN NOT NULL DEFAULT FALSE,
  version TEXT  PRIMARY KEY,
  source TEXT NOT NULL DEFAULT "manual",
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastmod DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE osreleases (
  short TEXT PRIMARY KEY,
  os TEXT PRIMARY KEY,
  long BOOLEAN NOT NULL DEFAULT FALSE,
  version TEXT  PRIMARY KEY,
  source TEXT NOT NULL DEFAULT "manual",
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastmod DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

-- 1 down

DROP TABLE IF EXISTS ssh2os;
DROP TABLE IF EXISTS banner2version;
